-- AI Runbook Step Executions table for individual step tracking
-- Logs the execution of each step within a runbook execution

CREATE TABLE IF NOT EXISTS ncm_ai_runbook_step_executions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Relationships
  runbook_execution_id UUID NOT NULL REFERENCES ncm_ai_runbook_executions(id) ON DELETE CASCADE,
  runbook_step_id UUID NOT NULL REFERENCES ncm_ai_runbook_steps(id) ON DELETE CASCADE,

  -- Execution details
  step_status VARCHAR(20) DEFAULT 'pending' CHECK (step_status IN ('pending', 'running', 'completed', 'failed', 'skipped')),
  step_input JSONB, -- Input provided to this step (from previous step or initial)
  step_output JSONB, -- Output generated by this step

  -- Timing
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  execution_time_seconds INTEGER,

  -- Error handling
  error_message TEXT,
  retry_attempt INTEGER DEFAULT 0,

  -- AI request tracking (links to existing ai_request_logs)
  ai_request_log_id UUID REFERENCES ncm_ai_request_logs(id),

  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Indexes for runbook step executions
CREATE INDEX IF NOT EXISTS idx_ncm_ai_runbook_step_executions_execution ON ncm_ai_runbook_step_executions(runbook_execution_id);
CREATE INDEX IF NOT EXISTS idx_ncm_ai_runbook_step_executions_step ON ncm_ai_runbook_step_executions(runbook_step_id);
CREATE INDEX IF NOT EXISTS idx_ncm_ai_runbook_step_executions_status ON ncm_ai_runbook_step_executions(step_status);
CREATE INDEX IF NOT EXISTS idx_ncm_ai_runbook_step_executions_ai_log ON ncm_ai_runbook_step_executions(ai_request_log_id);

-- Row Level Security (RLS)
ALTER TABLE ncm_ai_runbook_step_executions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role can manage AI runbook step executions" ON ncm_ai_runbook_step_executions FOR ALL USING (auth.role() = 'service_role');

-- Timestamp trigger for updated_at
CREATE TRIGGER update_ai_runbook_step_executions_updated_at
  BEFORE UPDATE ON ncm_ai_runbook_step_executions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();